import React from 'react';
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

import SendPage from '../components/SendPage';

const mockGetTokens = vi.fn();
const mockGetAssetBalance = vi.fn();
const mockUseWallet = vi.fn();

vi.mock('../services/WalletContext', () => ({
  useWallet: () => mockUseWallet(),
}));

vi.mock('../services/WalletService', () => ({
  walletService: {
    getTokens: (...args: unknown[]) => mockGetTokens(...args),
    getAssetBalance: (...args: unknown[]) => mockGetAssetBalance(...args),
    getAssetBalanceAtomic: () => ({ balanceAtomic: '0', unlockedBalanceAtomic: '0' }),
  },
}));

vi.mock('react-i18next', () => ({
  useTranslation: () => ({
    t: (key: string, fallback?: unknown) => {
      if (typeof fallback === 'string') return fallback;
      if (fallback && typeof fallback === 'object' && 'defaultValue' in (fallback as Record<string, unknown>)) {
        return String((fallback as Record<string, unknown>).defaultValue);
      }
      if (key === 'common.sal') return 'SAL';
      return key;
    },
    i18n: { language: 'en' },
  }),
}));

describe('SendPage asset gating', () => {
  beforeEach(() => {
    mockGetTokens.mockReset().mockResolvedValue(['salABCD']);
    mockGetAssetBalance.mockReset().mockReturnValue({
      balance: 0,
      unlockedBalance: 0,
      balanceSAL: 0,
      unlockedBalanceSAL: 0,
    });
    mockUseWallet.mockReset().mockReturnValue({
      validateAddress: vi.fn().mockResolvedValue(false),
      estimateFee: vi.fn().mockResolvedValue(0.0001),
      sendTransaction: vi.fn(),
      sendTransactionWithDetails: vi.fn(),
      sendTransactionWithDetailsAtomic: vi.fn(),
      refreshData: vi.fn(),
      sweepAllTransaction: vi.fn(),
      addContact: vi.fn(),
      updateContact: vi.fn(),
      removeContact: vi.fn(),
      balance: {
        balance: 500000000,
        unlockedBalance: 200000000,
        balanceSAL: 5,
        unlockedBalanceSAL: 2,
      },
      address: 'SalvMockAddress',
      contacts: [],
      subaddresses: [],
      updateContactUsage: vi.fn(),
    });
  });

  afterEach(() => {
    vi.clearAllMocks();
  });

  it('keeps asset send hidden on mainnet', () => {
    render(<SendPage enableAssetSend={false} />);

    expect(screen.queryByText('Asset Type')).toBeNull();
    expect(screen.getAllByText('SAL').length).toBeGreaterThan(0);
    expect(mockGetTokens).not.toHaveBeenCalled();
  });

  it('shows the asset selector only when explicitly enabled', async () => {
    render(<SendPage enableAssetSend />);

    expect(await screen.findByText('Asset Type')).not.toBeNull();
    await waitFor(() => expect(mockGetTokens).toHaveBeenCalledWith(''));
  });


  it('switches into SalPay mode when a SalPay URI is pasted', async () => {
    render(<SendPage enableAssetSend={false} />);

    const input = screen.getByPlaceholderText('SC1...');
    fireEvent.change(input, {
      target: {
        value: 'salvium:SC1salpaydestination?tx_amount=1.25&tx_asset=salABCD&tx_order=INV-7&tx_callback=https%3A%2F%2Fshop.example%2Fsalpay',
      },
    });

    expect(await screen.findByText('SalPay')).not.toBeNull();
    expect(screen.getByText('1.25 salABCD')).not.toBeNull();
    expect(screen.getByText('Callback: shop.example')).not.toBeNull();
    expect(screen.getByDisplayValue('1.25')).toHaveProperty('disabled', true);
    expect(screen.getByDisplayValue('salABCD')).toHaveProperty('disabled', true);
    expect(screen.queryByText('send.paymentId')).toBeNull();
    expect(mockGetTokens).not.toHaveBeenCalled();
  });


  it('blocks paying a SalPay request generated by the same wallet', async () => {
    const ownAddress = 'SC1ownsalpaydestination';
    mockUseWallet.mockReturnValue({
      validateAddress: vi.fn().mockResolvedValue(true),
      estimateFee: vi.fn().mockResolvedValue(0.0001),
      sendTransaction: vi.fn(),
      sendTransactionWithDetails: vi.fn(),
      sendTransactionWithDetailsAtomic: vi.fn(),
      refreshData: vi.fn(),
      sweepAllTransaction: vi.fn(),
      addContact: vi.fn(),
      updateContact: vi.fn(),
      removeContact: vi.fn(),
      balance: {
        balance: 500000000,
        unlockedBalance: 200000000,
        balanceSAL: 5,
        unlockedBalanceSAL: 2,
      },
      address: ownAddress,
      contacts: [],
      subaddresses: [{ address: 'SC1otherSubaddress' }],
      updateContactUsage: vi.fn(),
    });

    render(<SendPage enableAssetSend={false} />);

    fireEvent.change(screen.getByPlaceholderText('SC1...'), {
      target: {
        value: `salvium:${ownAddress}?tx_amount=1.25&tx_asset=SAL1`,
      },
    });

    expect(await screen.findByText('This SalPay request belongs to this wallet. Use a different wallet to test the payer flow.')).not.toBeNull();
    expect(screen.getByRole('button', { name: /Send SalPay/i })).toHaveProperty('disabled', true);
  });
});
