export enum TabView {
  DASHBOARD = 'DASHBOARD',
  SEND = 'SEND',
  RECEIVE = 'RECEIVE',
  HISTORY = 'HISTORY',
  STAKING = 'STAKING',
  ASSETS = 'ASSETS',
  MINING = 'MINING',
  SETTINGS = 'SETTINGS'
}
